# Tên của quy trình làm việc
name: Deploy Next.js site to Pages

# Chạy khi có code được đẩy lên nhánh main
on:
  push:
    branches: ["master"]

# Các quyền cần thiết cho Action
permissions:
  contents: read
  pages: write
  id-token: write

# Chỉ cho phép một lần triển khai đồng thời
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18" # Sử dụng phiên bản Node.js 18 như trong README
          cache: 'npm'
      - name: Install Dependencies
        run: npm install
      - name: Build with Next.js
        run: npm run build
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Tải lên thư mục `out` do Next.js tạo ra
          path: ./out

  # Công việc triển khai
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build # Phải chờ job 'build' chạy xong
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
